version: "3"


services: 
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    network_mode: host
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: postgres
    network_mode: host

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemons-luiz
    ports:
      - 5432:5432
